hidet-org/hidet

python/hidet/cli/main.py, python/hidet/graph/frontend/torch/__init__.py, python/hidet/graph/frontend/torch/dynamo_backends.py, python/hidet/utils/exiting.py, setup.py
See also [here](https://github.com/pytorch/pytorch/pull/93873) and [here](https://github.com/pytorch/pytorch/issues/91824).
=> [Dynamo] Add the entry point registration for dynamo

python/hidet/graph/ops/definitions/utils.py
=> [Fix] Update shape utility functions to expect Sequence instead of List

python/hidet/graph/frontend/onnx/onnx.py, python/hidet/graph/ops/definitions/utils.py
=> [Bugfix] 'double'->'float64' in onnx dtype conversion

python/hidet/graph/frontend/onnx/onnx.py, tests/graph/frontend/onnx/test_slice.py, tests/graph/frontend/onnx/utils.py
=> [ONNX] Fix the out of bound error in onnx slice function during importing

python/hidet/graph/ops/definitions/arithmetic.py, python/hidet/ir/compute/primitives.py, python/hidet/ir/task.py, python/hidet/ir/utils/__init__.py, python/hidet/ir/utils/expr_utils.py
=> [Fixbug] Reverse map of binary operator

python/hidet/graph/ops/definitions/activation.py
=> [Fixbug] Add attributes to Clip operator

python/hidet/graph/ir/flow_graph.py, python/hidet/graph/operator.py, python/hidet/graph/transforms/fuse_operator.py, tests/graph/operators/test_conv2d.py, tests/graph/operators/test_conv3d.py
=> [Graph] Refactor forward function of FlowGraph

python/hidet/graph/ops/definitions/reduce/reduce.py, python/hidet/testing/utils.py, tests/operators/test_reduce.py
=> [Fixbug] Use auto-scheduler for fp64 reduction

python/hidet/utils/stack_limit.py
=> [Stack] Allow the the ulimit stack size less than expected

python/hidet/graph/frontend/onnx/onnx.py, python/hidet/graph/frontend/torch/interpreter.py, python/hidet/graph/frontend/torch/register_functions.py, python/hidet/graph/frontend/torch/register_methods.py, python/hidet/graph/frontend/torch/register_modules.py, python/hidet/graph/ops/definitions/image.py, python/hidet/graph/tensor.py, tests/frontends/torch/test_torch_image.py, tests/operators/test_image.py
1. Add operator mapping for `torch.nn.Identity` and `operator.matmul`.
2. Fix bugs in mapping for `torch.Tensor.expand` and `hidet.ops.resize2d`.
=> [Frontend][Operator] Add missing operators for dinov2

python/hidet/graph/ops/definitions/normalize/norm.py, python/hidet/graph/ops/definitions/normalize/norm_f16.py, python/hidet/graph/ops/definitions/normalize/resolve.py, tests/frontends/torch/test_torch_to.py, tests/operators/test_complex.py, tests/script/test_parallel.py
Fix test warnings and allow the norm support dynamic shape.
=> [Fixbug] Fix test warnings and the incompatibility of two recent PRs

python/hidet/graph/ops/definitions/fusion/fused_operator.py
Now, we can pass the following test script
```python
import hidet
w1 = hidet.randn([1], device='cuda', dtype='float16')
w2 = hidet.randn_like(w1)
def hidet_make_causal_mask(seq_len, dtype, device, past_key_values_length):
x = hidet.ops.tri(
n=seq_len, m=seq_len + past_key_values_length, k=past_key_values_length, dtype=dtype, device=device
)
t = (1 - x) * float(dtype._min_value)
return t + w1, t + w2
s = hidet.symbol(["seqlen", "pastseqlen"], device='cuda')
y = hidet_make_causal_mask(s.shape[0], s.dtype, s.device, s.shape[1])
graph = hidet.trace_from(list(y), s)
from hidet.graph.transforms.subgraph_rewrite import subgraph_rewrite_pass
from hidet.graph.transforms.automatic_mix_precision import automatic_mix_precision_pass
from hidet.graph.transforms.resolve_variant import …
```
=> [Fixbug] Fix a bug when fused operator has no input

python/hidet/graph/frontend/torch/register_functions.py, python/hidet/graph/ops/attention/attention.py, python/hidet/graph/ops/attention/attention_mask.py, python/hidet/graph/transforms/graph_patterns/attn_patterns.py, tests/frontends/torch/test_torch_sdpa.py, tests/operators/test_attention.py
Previously, attention requires seq_len_q == seq_len_k == seq_len_v.
With this PR, seq_len_q != seq_len_k is supported. (seq_len_k ==seq_len_v still required).
Also fix some bugs related to seq_len sizes not multiple of 8. Arbitrary seq_len sizes are now supported.
=> [Operator] Add support for cross attention

apps/compile_server/Dockerfile, apps/compile_server/README.md, apps/compile_server/app.py, apps/compile_server/requirements.txt, apps/compile_server/resources/compilation.py, apps/compile_server/resources/compile_worker.py, apps/compile_server/run.py, apps/compile_server/run.sh, python/hidet/apps/compile_server/compilation.py, python/hidet/option.py
Allow the user to specify which repo to use
```python
hidet.option.compile_server.repo('https://github.com/hidet-org/hidet', 'main')  
```
=> [Compile Server] Allow the user to specify the repo and branch/tag to use 

python/hidet/graph/ops/attention/attention.py, python/hidet/graph/ops/attention/attention_mask.py, python/hidet/graph/ops/matmul/resolve.py, python/hidet/graph/transforms/graph_patterns/attn_patterns.py, python/hidet/ir/primitives/cuda/cvt.py
This will allow dynamic shape models such as llama to use fmha.
=> [Operator] Update attention for dynamic shape

python/hidet/graph/ops/arithmetic.py, python/hidet/graph/transforms/graph_patterns/base.py, python/hidet/graph/transforms/graph_patterns/transform_patterns.py
Assuming `U1` and `U2` are unary elementwise operators, and `B` is a binary elementwise operator.
Introduce a new fused operator called Composite Elementwise Operation, where `comp_elemwise(x, U1, U2, B) = B(U1(x), U2(x))`.
Also add subgraph rewrite rule. This allows for more fusion opportunity.
=> [Operator] Composite Elementwise Operation

python/hidet/drivers/build_task.py, python/hidet/ir/builders/stmt_builder.py, python/hidet/ir/primitives/cuda/mma.py, python/hidet/ir/schedulers/cpu/scheduler.py, python/hidet/runtime/compiled_graph.py, python/hidet/runtime/compiled_task.py, python/hidet/utils/py.py, python/hidet/utils/trace_utils.py
=> [CPU][Scheduler] Use mutli-threads for autl-scheduler

python/hidet/graph/frontend/torch/register_functions.py, python/hidet/graph/frontend/torch/register_methods.py, python/hidet/graph/ops/__init__.py, python/hidet/graph/ops/arithmetic.py, python/hidet/graph/ops/image.py, python/hidet/graph/ops/normalize/lp.py, python/hidet/graph/ops/pool.py, python/hidet/graph/transforms/graph_patterns/conv2d_patterns.py, python/hidet/ir/primitives/cuda/math/float16.py
This is a continuation of #347.
1. Add LP normalization task (ToDo: schedule template)
2. Add torch mappings for normalize, clone, zero_, exp, chunk
3. Add ceil_mode=True support for pool2d
4. Fix dtype issue in resize
5. Fix other bugs in pad, conv2d_pattern
=> [Torch][Operator] More torchvision model support

python/hidet/graph/frontend/torch/register_functions.py, python/hidet/graph/ops/__init__.py, python/hidet/graph/ops/linear.py
Add an ad-hoc implementation of einsum based on pattern matching. Only supports batched matmul.
=> [Operator] Add einsum

apps/compile_server/resources/auth.py, python/hidet/graph/frontend/torch/register_functions.py, python/hidet/graph/ops/conv2d/conv2d.py, python/hidet/graph/ops/conv2d/conv2d_gemm.py, python/hidet/graph/ops/conv2d/resolve.py, python/hidet/graph/ops/pool.py, python/hidet/graph/transforms/__init__.py, python/hidet/graph/transforms/conv_channel_last.py, scripts/regression/model_performance.py, scripts/regression/regression_data.json, scripts/regression/requirements.txt, tests/operators/test_conv2d.py
This PR aims to improve the performance of CNNs. The main changes include:
1. Add a graph pass that converts and maintains image tensors to channel last format throughout the graph as long as possible.
2. Move the padding operation into the schedule of conv2d. Also get rid of register writeback to global memory and force shared memory writeback.
3. Add various torchvision models to regression.
=> [Operator][Graph][Regression] CNN optimizations

python/hidet/graph/ops/matmul/batch_matmul.py, python/hidet/graph/transforms/conv_channel_last.py, scripts/regression/op_performance.py
Fix a bug in batch_matmul schedule. Fix two bugs in channel last pass.
=> [Graph] Minor bug fixes

python/hidet/graph/frontend/torch/register_functions.py
Add operators lshift, rshift, mod
=> [Graph][Dynamo Backend] Lshift/Rshift/Mod

python/hidet/backend/codegen.py
=> [Fixbug] Fix a bug related to c/c++ integer promotion

.github/requirements-ci.txt, .github/scripts/bench/bench_op.py, .github/scripts/bench/bench_transformer.py, .github/scripts/bench/bench_utils.py, .github/scripts/bench/bench_vision.py, .github/scripts/db_utils.py, .github/scripts/run_tests.py, .github/scripts/start_instances.py, .github/scripts/stop_instances.py, .github/scripts/upload_results.py, .github/workflows/regression.yaml, apps/compile_server/Dockerfile, apps/compile_server/resources/compilation.py, python/hidet/apps/compile_server/compilation.py, python/hidet/backend/build.py, python/hidet/drivers/build_module.py, python/hidet/ir/target.py, python/hidet/option.py, requirements.txt
Also add support for cpu arch option to allow Compile Server to target a specific CPU arch.
Ubuntu ver. for Compile Server is bumped for compatibility with newer CPU gens.
Numpy ver. is bumped for compatibility.
=> [CI] Add CI workflow and scripts

python/hidet/graph/ops/matmul/batch_matmul.py, python/hidet/graph/ops/matmul/matmul_cublas.py, python/hidet/graph/ops/matmul/matmul_f16.py, python/hidet/graph/ops/utils/schedule_utils.py, python/hidet/ir/utils/call_graph.py
Also fix bug in call graph generation.
=> [Operator] Add cublas to matmul tune space

README.md
Fix the link to "Optimize ONNX models".
=> [README] Fix ONNX link

apps/compile_server/resources/compilation.py
=> [Compile Server] Fetch repo before checking out

include/hidet/runtime/cuda/cudnn.h, src/hidet/runtime/cuda/cudnn.cpp
Format cudnn.cpp and cudnn.h files. Required to merge with CentML/hidet
=> [STYLE] Format cpp/h files

python/hidet/version.py, setup.py
Promote the version  0.4.0.dev -> 0.4.0
=> Promote the version to 0.4.0

include/hidet/runtime/llm/tokenizer/decoders.h
=> [BUG] Add missed include

.github/actions/action.yaml, python/hidet/version.py, scripts/wheel/build_wheel.sh, scripts/wheel/dockerfiles/manylinux1/Dockerfile, scripts/wheel/dockerfiles/manylinux_2_28_x86_64/Dockerfile, setup.py
- build wheel with `manylinux_2_28_x86_64`
- v0.4.0 -> v0.4.1
=> [BUILD] Build wheel with `manylinux_2_28_x86_64`

python/hidet/version.py, setup.py
Fix forgotten version promotion
=> [Version] v0.4.1 -> v0.5.0.dev

.github/workflows/publish-pypi.yaml
Update docker image for Publish workflow to corresponds Tests workflow
=> [CI] Update docker image for Publish workflow

python/hidet/graph/ops/quant/symmetric.py, python/hidet/version.py
Revert
https://github.com/hidet-org/hidet/pull/480
https://github.com/hidet-org/hidet/pull/481
=> Revert 2 PRs for quant fix

apps/compile_server/requirements.txt
Without this sync Regression fails
=> [BUG] Hot fix comp server requirements.txt

python/hidet/graph/frontend/torch/registry.py
Chery-pick fix the bug that appeared with torch==2.6.0
=> [BUG] Fix for torch==2.6.0 (#749)

python/hidet/graph/frontend/torch/registry.py
Fix in #491 a little bit incorrect. 
Fix it
=> [BUG] Fix for torch==2.6.0. Attempt 2 (#755)
